#!/usr/bin/env python

import json
import random
import sys
import dotenv
import os
from os.path import dirname, join

# Loading environment variables from .env file.
DOTENV_PATH = join(dirname(__file__), ".env")
dotenv.load_dotenv(DOTENV_PATH)

# Environment variables:
DATABASE = os.environ.get("DATABASE")
MASTER_KEY = os.environ.get("MASTER_KEY")


def readDB() -> str:
    """Reads the database"""
    with open(DATABASE, "r", encoding="utf-8") as handler:
        return json.load(handler)


def writeDB(content: None) -> None:
    """Writes to the database"""
    with open(DATABASE, "w", encoding="utf-8") as handler:
        json.dump(content, handler)


def generate(size: int) -> str:
    """Generates a unique ID"""
    rnd = ""
    size = abs(size) + 1 if size == 0 else abs(size)

    while len(rnd) <= 10:
        rnd += str(random.choice(range(size * 10)))

    return rnd


def create() -> None:
    """Creates a new password data"""
    data = readDB()

    sitename = input("Site name or App name: ")
    username = input("User name: ")
    password = input("Password: ")

    if sitename != "" and username != "" and password != "":
        ID = generate(len(data))
        data[ID] = {}
        data[ID]["sitename"] = sitename
        data[ID]["username"] = username
        data[ID]["password"] = password
        print("Password saved.")

    else:
        print("Any placeholder cannot be empty.")
        print("Password is not saved.")

    writeDB(data)


def main() -> None:
    # Check whether the script was run only with the script command. If it was
    # run by any other command then ignore them. Otherwise, only ignore the
    # script name. See issue: #2
    args = []

    if args in ["python", "python3", "py"]:
        args = sys.argv[2:]

    else:
        args = sys.argv[1:]

    # Warning message if the program is run without any command. See issue: #4
    if len(args) == 0:
        print("Expected at least 1 argument, got 0")
        exit(1)

    # Store the command. It increases code readability.
    command = args[0]

    # Handles the arguments.
    if command == "create":
        create()

    else:
        print(f"Command not found: {command}")


# User authentication. Added after issue: #7
try:
    userKey = input('Master key: ')

    if userKey == MASTER_KEY:
        main()

    else:
        print("Sorry, incorrect password.")
        exit(1)

# Handle keyboard interruption. Also see issue: #8
except KeyboardInterrupt:
    # Sometime error message appears at prompts for some reason. To avoid it,
    # print a blank line before the error message.
    print()
    print('User aborted!!')

# Also handle other errors and give a readable output.
except Exception as error:
    print(error)
